# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Titanic Design
email: contact@titanic.design
baseurl: ""
url: "http://titanic.design"
repository: titanic-design/titanic-design.github.io

seo:
  title: Large Scale Rapid Prototyping - Titanic Design
  description: Titanic Design specializes in providing titanic scale 3D printing services for clients around the world. Our goal is to provide the tools to transform concepts into physical artifacts. Opening new possibilities across sectors that have traditionally been unable to access high quality additive manufacturing.

github: [metadata]
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/media"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
